import {
  User,
  Team,
  TeamMembership,
  Invitation,
  Property,
  Client,
  Opportunity,
  FollowUp,
  Visit,
  Match,
  Notification,
  DashboardStats,
} from '../types';

export const mockUsers: User[] = [
  {
    id: 'usr_101',
    fullName: 'مهدی رضایی',
    mobile: '۰۹۱۲۳۴۵۶۷۸۹',
    email: 'm.rezaei@amlakino.ir',
    role: 'agent',
    teamId: 'team_tehran_1',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    licenseCode: 'A-4482',
    passwordHash: 'e6c276404fb9457fb54315cee407b40d00e5ebfb', // 123456
    salt: 'salt_101',
    createdAt: '1403/01/15',
  },
  {
    id: 'usr_102',
    fullName: 'سارا امینی',
    mobile: '۰۹۱۲۲۲۲۳۳۴۴',
    email: 's.amini@amlakino.ir',
    role: 'agent',
    teamId: 'team_tehran_1',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    licenseCode: 'A-7719',
    passwordHash: 'e6c276404fb9457fb54315cee407b40d00e5ebfb',
    salt: 'salt_102',
    createdAt: '1403/02/10',
  },
  {
    id: 'usr_mgr_1',
    fullName: 'مهندس علیرضا تهرانی',
    mobile: '۰۹۱۲۹۹۹۰۰۰۰',
    email: 'manager@amlakino.ir',
    role: 'manager',
    teamId: 'team_tehran_1',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    licenseCode: 'M-1100',
    passwordHash: 'e6c276404fb9457fb54315cee407b40d00e5ebfb',
    salt: 'salt_mgr',
    createdAt: '1402/08/10',
  },
  {
    id: 'usr_103',
    fullName: 'آرش نوری',
    mobile: '۰۹۱۲۸۸۸۹۹۰۰',
    email: 'a.nouri@amlakino.ir',
    role: 'agent',
    teamId: 'team_tehran_1',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    licenseCode: 'A-9921',
    passwordHash: 'e6c276404fb9457fb54315cee407b40d00e5ebfb',
    salt: 'salt_103',
    createdAt: '1403/03/15',
  },
  {
    id: 'usr_104',
    fullName: 'کامران شریفی (مشاور مستقل خارج از تیم)',
    mobile: '۰۹۱۹۴۴۴۷۷۸۸',
    email: 'k.sharifi@amlakino.ir',
    role: 'agent',
    teamId: undefined, // Outside agent
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    licenseCode: 'IND-302',
    passwordHash: 'e6c276404fb9457fb54315cee407b40d00e5ebfb',
    salt: 'salt_104',
    createdAt: '1403/04/01',
    agentMode: 'independent',
    subscriptionStatus: 'active',
  },
];

export const mockCurrentUser: User = mockUsers[0];

export const mockTeam: Team = {
  id: 'team_tehran_1',
  name: 'گروه مشاورین املاک بارمان (سعادت‌آباد)',
  licenseNumber: 'ص/۹۹/۴۱۲۰',
  managerId: 'usr_mgr_1',
  city: 'تهران',
  address: 'سعادت‌آباد، میدان کاج، خیابان سرو غربی، پلاک ۴۲، طبقه ۳',
  phone: '۰۲۱-۲۲۰۸۹۰۰۰',
  createdAt: '1402/08/10',
};

export const initialTeamMemberships: TeamMembership[] = [
  {
    id: 'tmb_1',
    teamId: 'team_tehran_1',
    userId: 'usr_mgr_1',
    role: 'manager',
    joinedAt: '1402/08/10',
    status: 'active',
    createdAt: '1402/08/10',
  },
  {
    id: 'tmb_2',
    teamId: 'team_tehran_1',
    userId: 'usr_101',
    role: 'agent',
    joinedAt: '1403/01/15',
    status: 'active',
    createdAt: '1403/01/15',
  },
  {
    id: 'tmb_3',
    teamId: 'team_tehran_1',
    userId: 'usr_102',
    role: 'agent',
    joinedAt: '1403/02/10',
    status: 'active',
    createdAt: '1403/02/10',
  },
];

export const initialInvitations: Invitation[] = [
  {
    id: 'inv_1',
    teamId: 'team_tehran_1',
    teamName: 'گروه مشاورین املاک بارمان (سعادت‌آباد)',
    inviterId: 'usr_mgr_1',
    inviterName: 'مهندس علیرضا تهرانی',
    inviteeMobile: '۰۹۱۲۷۷۷۶۶۵۵',
    inviteeEmail: 'k.yazdani@gmail.com',
    inviteeName: 'کامران یزدانی',
    role: 'agent',
    status: 'pending',
    token: 'inv_token_abc789',
    expiresAt: '۱۴۰۳/۰۷/۲۰',
    createdAt: '۱۴۰۳/۰۷/۰۱',
  },
];

export const initialProperties: Property[] = [
  {
    id: 'prop_1',
    code: 'AML-1042',
    title: 'آپارتمان ۱۴۵ متری تک‌واحدی، صراف‌های جنوبی',
    dealType: 'sale',
    propertyType: 'apartment',
    area: 145,
    totalPrice: 22_500_000_000, // 22.5 Billion Toman
    pricePerMeter: 155_000_000,
    bedrooms: 3,
    floor: 4,
    totalFloors: 5,
    unitsPerFloor: 1,
    yearBuilt: 1400,
    parking: true,
    elevator: true,
    storage: true,
    balcony: true,
    district: 'سعادت‌آباد',
    city: 'تهران',
    addressSummary: 'سعادت‌آباد، صراف‌های جنوبی، کوچه ۲۳ شرقی',
    fullAddress: 'سعادت‌آباد، صراف‌های جنوبی، کوچه ۲۳ شرقی، پلاک ۱۴، زنگ ۴',
    description: 'سالن پرده‌خور غرق در نور جنوب، نقشه مهندسی بدون کوچک‌ترین پرتی، ۲ پارکینگ سندی باکس، متریال برند وارداتی، لابی مجلل مبله با سرایداری مقیم.',
    features: ['مستر روم', '۲ پارکینگ سندی', 'لابی مجلل', 'سرایدار مقیم', 'روف گاردن', 'اسپلیت و داکت'],
    ownerName: 'دکتر صمدی',
    ownerPhone: '۰۹۱۲۱۱۱۴۳۲۱',
    status: 'active',
    ownerId: 'usr_101',
    privacyState: 'private',
    agentId: 'usr_101',
    agentName: 'مهدی رضایی',
    teamId: 'team_tehran_1',
    createdAt: '۱۴۰۳/۰۶/۲۸',
    updatedAt: '۱۴۰۳/۰۷/۰۱',
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80'],
  },
  {
    id: 'prop_2',
    code: 'AML-1043',
    title: '۱۱۰ متر ۲ خوابه شیک، نوساز، بلوار فرهنگ',
    dealType: 'rent',
    propertyType: 'apartment',
    area: 110,
    deposit: 1_200_000_000, // 1.2 Billion Toman
    monthlyRent: 35_000_000, // 35 Million Toman
    bedrooms: 2,
    floor: 2,
    totalFloors: 6,
    unitsPerFloor: 2,
    yearBuilt: 1402,
    parking: true,
    elevator: true,
    storage: true,
    balcony: true,
    district: 'سعادت‌آباد',
    city: 'تهران',
    addressSummary: 'سعادت‌آباد، بلوار فرهنگ، خیابان پیوند',
    fullAddress: 'سعادت‌آباد، بلوار فرهنگ، خیابان پیوند، پلاک ۱۸، واحد ۳',
    description: 'فول فرنیش بوش آلمان، کمد دیواری‌های جادار، تراس قابل چیدمان، مناسب خانواده یا مجرد موجه.',
    features: ['آسانسور', 'پارکینگ', 'انباری', 'نگهبانی ۲۴ ساعته', 'سیستم اطفا حریق'],
    ownerName: 'خانم مهندس طاهری',
    ownerPhone: '۰۹۱۲۲۲۲۷۸۹۰',
    status: 'active',
    ownerId: 'usr_101',
    privacyState: 'shared',
    agentId: 'usr_101',
    agentName: 'مهدی رضایی',
    teamId: 'team_tehran_1',
    createdAt: '۱۴۰۳/۰۶/۲۹',
    updatedAt: '۱۴۰۳/۰۷/۰۲',
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop&q=80'],
  },
  {
    id: 'prop_3',
    code: 'AML-1044',
    title: 'ویلای ۴۵۰ متری دوبلکس، نیاوران گل‌سنگ',
    dealType: 'sale',
    propertyType: 'villa',
    area: 450,
    totalPrice: 85_000_000_000, // 85 Billion Toman
    pricePerMeter: 188_000_000,
    bedrooms: 4,
    floor: 1,
    totalFloors: 2,
    yearBuilt: 1398,
    parking: true,
    elevator: true,
    storage: true,
    balcony: true,
    district: 'نیاوران',
    city: 'تهران',
    addressSummary: 'نیاوران، خیابان یاسر، کوچه گل‌سنگ',
    fullAddress: 'نیاوران، خیابان یاسر، بن‌بست یاسمن، پلاک ۶',
    description: 'استخر روباز ۴ فصل با سیستم تصفیه آب گرم، محوطه‌سازی هلندی با آلاچیق، سوییت مجزا برای مهمان، ویو ابدی کل تهران.',
    features: ['استخر ۴ فصل', 'سونا و جکوزی', 'روف گاردن ۳۶۰ درجه', 'سوئیت سرایداری', 'سیستم هوشمند KNX'],
    ownerName: 'حاج آقا کاظمی',
    ownerPhone: '۰۹۱۲۳۳۳۹۹۸۸',
    status: 'active',
    ownerId: 'usr_101',
    privacyState: 'private',
    agentId: 'usr_101',
    agentName: 'مهدی رضایی',
    teamId: 'team_tehran_1',
    createdAt: '۱۴۰۳/۰۶/۲۵',
    updatedAt: '۱۴۰۳/۰۷/۰۳',
    images: ['https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&auto=format&fit=crop&q=80'],
  },
  {
    id: 'prop_4',
    code: 'AML-1045',
    title: 'موقعیت اداری ۹۰ متر تابلوخور، میدان کاج',
    dealType: 'rent',
    propertyType: 'office',
    area: 90,
    deposit: 600_000_000,
    monthlyRent: 48_000_000,
    bedrooms: 2,
    floor: 3,
    totalFloors: 5,
    unitsPerFloor: 3,
    yearBuilt: 1396,
    parking: true,
    elevator: true,
    storage: true,
    balcony: false,
    district: 'سعادت‌آباد',
    city: 'تهران',
    addressSummary: 'میدان کاج، ابتدای سرو شرقی',
    fullAddress: 'میدان کاج، ابتدای سرو شرقی، ساختمان پلاس، واحد ۴',
    description: 'مناسب مطب پزشکان، دفتر وکالت و شرکت‌های معتبر مهندسی، دسترسی عالی به مترو و ایستگاه تاکسی.',
    features: ['تابلوخور عالی', 'آسانسور ۱۰ نفره', 'کابل‌کشی شبکه', 'دوربین مداربسته'],
    ownerName: 'آقای بهرامی',
    ownerPhone: '۰۹۱۲۴۴۴۱۱۲۲',
    status: 'active',
    ownerId: 'usr_102', // Belongs to agent Sara Amini
    privacyState: 'private',
    agentId: 'usr_102',
    agentName: 'سارا امینی',
    teamId: 'team_tehran_1',
    createdAt: '۱۴۰۳/۰۷/۰۱',
    updatedAt: '۱۴۰۳/۰۷/۰۳',
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=80'],
  },
  {
    id: 'prop_5',
    code: 'AML-1046',
    title: 'آپارتمان ۹۲ متری ۲ خوابه، خوش‌نقشه، سعادت‌آباد علامه',
    dealType: 'sale',
    transactionType: 'sale',
    propertyType: 'apartment',
    area: 92,
    totalPrice: 7_500_000_000, // 7.5 Billion Toman (Test Case 1)
    price: 7_500_000_000,
    pricePerMeter: 81_520_000,
    bedrooms: 2,
    floor: 3,
    totalFloors: 5,
    unitsPerFloor: 2,
    yearBuilt: 1400,
    parking: true,
    elevator: true,
    storage: true,
    balcony: true,
    district: 'سعادت‌آباد',
    neighborhood: 'سعادت‌آباد',
    city: 'تهران',
    addressSummary: 'سعادت‌آباد، علامه جنوبی، کوچه ۳۴ غربی',
    fullAddress: 'سعادت‌آباد، علامه جنوبی، کوچه ۳۴ غربی، پلاک ۱۲، واحد ۶',
    description: 'نورگیر عالی از دو جهت شمال و جنوب، نقشه مهندسی تفکیکی، پارکینگ همکف سندی، دسترسی فوق‌العاده به مراکز خرید و بزرگراه یادگار.',
    features: ['آسانسور', 'پارکینگ', 'انباری', 'بالکن', 'کابینت های‌گلاس', 'سیستم پکیج'],
    ownerName: 'آقای شمس‌الدینی',
    ownerPhone: '۰۹۱۲۳۴۵۹۹۱۱',
    status: 'active',
    availabilityStatus: 'available',
    ownerId: 'usr_101',
    privacyState: 'shared',
    agentId: 'usr_101',
    agentName: 'مهدی رضایی',
    teamId: 'team_tehran_1',
    createdAt: '۱۴۰۳/۰۷/۰۳',
    updatedAt: '۱۴۰۳/۰۷/۰۴',
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&auto=format&fit=crop&q=80'],
  },
  {
    id: 'prop_6',
    code: 'AML-1047',
    title: 'آپارتمان ۱۱۰ متری ۲ خوابه، سالن دلباز، سعادت‌آباد سرو غربی',
    dealType: 'sale',
    transactionType: 'sale',
    propertyType: 'apartment',
    area: 110,
    totalPrice: 7_800_000_000, // 7.8 Billion Toman (Partial match deviation demo: 110 sqm)
    price: 7_800_000_000,
    pricePerMeter: 70_900_000,
    bedrooms: 2,
    floor: 2,
    totalFloors: 5,
    unitsPerFloor: 2,
    yearBuilt: 1399,
    parking: true,
    elevator: true,
    storage: true,
    balcony: true,
    district: 'سعادت‌آباد',
    neighborhood: 'سعادت‌آباد',
    city: 'تهران',
    addressSummary: 'سعادت‌آباد، سرو غربی، خیابان صدف',
    fullAddress: 'سعادت‌آباد، سرو غربی، خیابان صدف، مجتمع صدف، واحد ۴',
    description: 'پلن بی‌نقص با سالن وسیع پرده‌خور، آشپزخانه جادار، متراژ ۱۱۰ متر واقعی با سند تک‌برگ آماده انتقال.',
    features: ['آسانسور', 'پارکینگ سندی', 'انباری سندی', 'بالکن کاربردی', 'اسپلیت'],
    ownerName: 'خانم مهندس صادقی',
    ownerPhone: '۰۹۱۲۴۵۶۷۸۹۰',
    status: 'active',
    availabilityStatus: 'available',
    ownerId: 'usr_101',
    privacyState: 'shared',
    agentId: 'usr_101',
    agentName: 'مهدی رضایی',
    teamId: 'team_tehran_1',
    createdAt: '۱۴۰۳/۰۷/۰۲',
    updatedAt: '۱۴۰۳/۰۷/۰۴',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop&q=80'],
  },
];

export const initialClients: Client[] = [
  {
    id: 'cli_1',
    fullName: 'مهندس فرشید پارسا',
    mobile: '۰۹۱۲۵۵۵۹۸۷۶',
    role: 'buyer',
    status: 'active',
    desiredDealType: 'sale',
    desiredPropertyTypes: ['apartment'],
    budgetMin: 20_000_000_000,
    budgetMax: 24_000_000_000,
    minArea: 130,
    maxArea: 160,
    minBedrooms: 3,
    desiredDistricts: ['سعادت‌آباد', 'شهرک غرب'],
    mustHaveElevator: true,
    mustHaveParking: true,
    notes: 'خریدار نقدی قطعی با بودجه آماده در حساب. تأکید ویژه روی نورگیر بودن سالن و داشتن حداقل ۲ پارکینگ.',
    ownerId: 'usr_101',
    privacyState: 'private',
    agentId: 'usr_101',
    agentName: 'مهدی رضایی',
    teamId: 'team_tehran_1',
    createdAt: '۱۴۰۳/۰۷/۰۱',
    lastContactAt: '۱۴۰۳/۰۷/۰۴',
  },
  {
    id: 'cli_2',
    fullName: 'سرکار خانم دکتر معتمدی',
    mobile: '۰۹۱۲۶۶۶۳۲۱۰',
    role: 'tenant',
    status: 'active',
    desiredDealType: 'rent',
    desiredPropertyTypes: ['apartment'],
    maxDeposit: 1_500_000_000,
    maxMonthlyRent: 40_000_000,
    minArea: 100,
    maxArea: 130,
    minBedrooms: 2,
    desiredDistricts: ['سعادت‌آباد', 'پاسداران'],
    mustHaveElevator: true,
    mustHaveParking: true,
    notes: 'پزشک متخصص، متقاضی واحد تمیز و نوساز با سرایداری مقیم و سکوت کامل در طول روز.',
    ownerId: 'usr_101',
    privacyState: 'shared',
    agentId: 'usr_101',
    agentName: 'مهدی رضایی',
    teamId: 'team_tehran_1',
    createdAt: '۱۴۰۳/۰۶/۳۰',
    lastContactAt: '۱۴۰۳/۰۷/۰۳',
  },
  {
    id: 'cli_3',
    fullName: 'حاج علیرضا اکبری',
    mobile: '۰۹۱۲۷۷۷۸۸۹۹',
    role: 'investor',
    status: 'negotiation',
    desiredDealType: 'sale',
    desiredPropertyTypes: ['villa', 'penthouse'],
    budgetMin: 70_000_000_000,
    budgetMax: 90_000_000_000,
    minArea: 400,
    desiredDistricts: ['نیاوران', 'فرمانیه', 'زعفرانیه'],
    mustHaveParking: true,
    notes: 'سازنده قدیمی بازار، تمایل به خرید ویلای لوکس با حیاط مشجر در منطقه ۱ دارد.',
    ownerId: 'usr_102', // Belongs to Sara Amini
    privacyState: 'private',
    agentId: 'usr_102',
    agentName: 'سارا امینی',
    teamId: 'team_tehran_1',
    createdAt: '۱۴۰۳/۰۶/۲۰',
    lastContactAt: '۱۴۰۳/۰۷/۰۲',
  },
  {
    id: 'cli_4',
    fullName: 'پیمان حسینی',
    name: 'پیمان حسینی',
    mobile: '۰۹۱۲۳۳۳۴۴۵۵',
    phone: '۰۹۱۲۳۳۳۴۴۵۵',
    role: 'buyer',
    status: 'active',
    desiredDealType: 'sale',
    transactionType: 'sale',
    desiredPropertyTypes: ['apartment'],
    propertyType: 'apartment',
    budgetMin: 7_000_000_000,
    minBudget: 7_000_000_000,
    budgetMax: 8_000_000_000,
    maxBudget: 8_000_000_000,
    minArea: 80,
    maxArea: 100,
    minBedrooms: 2,
    bedrooms: 2,
    desiredDistricts: ['شمال تهران', 'سعادت‌آباد'],
    preferredRegions: ['شمال تهران', 'سعادت‌آباد'],
    preferredCity: 'تهران',
    mustHaveElevator: true,
    mustHaveParking: true,
    requirements: ['پارکینگ', 'آسانسور'],
    urgency: 'high',
    notes: 'خریدار نقد ۲ خوابه در محدوده شمال تهران و سعادت‌آباد با بودجه ۷ الی ۸ میلیارد تومان و حتماً پارکینگ و آسانسور.',
    ownerId: 'usr_101',
    privacyState: 'shared',
    agentId: 'usr_101',
    agentName: 'مهدی رضایی',
    teamId: 'team_tehran_1',
    createdAt: '۱۴۰۳/۰۷/۰۲',
    lastContactAt: '۱۴۰۳/۰۷/۰۴',
  },
  {
    id: 'cli_5',
    fullName: 'دکتر محمدرضا شایگان',
    name: 'دکتر محمدرضا شایگان',
    mobile: '۰۹۱۲۴۴۴۵۵۶۶',
    phone: '۰۹۱۲۴۴۴۵۵۶۶',
    role: 'buyer',
    status: 'active',
    desiredDealType: 'sale',
    transactionType: 'sale',
    desiredPropertyTypes: ['apartment'],
    propertyType: 'apartment',
    budgetMin: 21_000_000_000,
    minBudget: 21_000_000_000,
    budgetMax: 24_000_000_000,
    maxBudget: 24_000_000_000,
    minArea: 135,
    maxArea: 160,
    minBedrooms: 3,
    bedrooms: 3,
    desiredDistricts: ['سعادت‌آباد'],
    preferredRegions: ['سعادت‌آباد'],
    preferredCity: 'تهران',
    mustHaveElevator: true,
    mustHaveParking: true,
    requirements: ['پارکینگ سندی', 'آسانسور', '۳ خواب'],
    urgency: 'high',
    notes: 'متقاضی قطعی خرید آپارتمان ۳ خوابه در سعادت‌آباد؛ سرمایه نقد آماده در حساب.',
    ownerId: 'usr_102', // Sara Amini owns this client!
    privacyState: 'shared', // Shared with team colleagues!
    agentId: 'usr_102',
    agentName: 'سارا امینی',
    teamId: 'team_tehran_1',
    createdAt: '۱۴۰۳/۰۷/۰۳',
    lastContactAt: '۱۴۰۳/۰۷/۰۴',
  },
];

export const initialFollowUps: FollowUp[] = [
  {
    id: 'flw_1',
    title: 'تماس با مهندس پارسا برای پیشنهاد فایل صراف‌ها',
    clientId: 'cli_1',
    clientName: 'مهندس فرشید پارسا',
    clientPhone: '۰۹۱۲۵۵۵۹۸۷۶',
    propertyId: 'prop_1',
    propertyTitle: 'آپارتمان ۱۴۵ متری تک‌واحدی، صراف‌های جنوبی',
    dueDate: 'امروز',
    dueTime: '۱۶:۳۰',
    priority: 'high',
    status: 'pending',
    type: 'call',
    notes: 'فایل صراف‌ها تطابق ۹۶ درصدی با بودجه و لوکیشن ایشان دارد؛ برای بازدید فردا هماهنگ شود.',
    ownerId: 'usr_101',
    privacyState: 'private',
    agentId: 'usr_101',
    createdAt: '۱۴۰۳/۰۷/۰۴',
  },
  {
    id: 'flw_2',
    title: 'پیگیری ارسال قرارداد رهن واحد فرهنگ برای خانم دکتر معتمدی',
    clientId: 'cli_2',
    clientName: 'خانم دکتر معتمدی',
    clientPhone: '۰۹۱۲۶۶۶۳۲۱۰',
    propertyId: 'prop_2',
    propertyTitle: '۱۱۰ متر ۲ خوابه شیک، نوساز، بلوار فرهنگ',
    dueDate: 'امروز',
    dueTime: '۱۸:۰۰',
    priority: 'high',
    status: 'pending',
    type: 'meeting',
    notes: 'مالک تخفیف جزئی روی رهن داده، پیش‌نویس چک‌های صیادی بررسی شود.',
    ownerId: 'usr_101',
    privacyState: 'shared',
    agentId: 'usr_101',
    createdAt: '۱۴۰۳/۰۷/۰۴',
  },
  {
    id: 'flw_3',
    title: 'استعلام سند تک‌برگ و تسویه شهرداری ملک نیاوران',
    clientId: 'cli_3',
    clientName: 'حاج علیرضا اکبری',
    clientPhone: '۰۹۱۲۷۷۷۸۸۹۹',
    propertyId: 'prop_3',
    propertyTitle: 'ویلای ۴۵۰ متری دوبلکس، نیاوران گل‌سنگ',
    dueDate: 'دیروز',
    dueTime: '۱۱:۰۰',
    priority: 'high',
    status: 'overdue',
    type: 'contract',
    notes: 'مدیر املاک تأکید کرده قبل از نشست روز چهارشنبه، استعلام ثبتی ملک قطعی شود.',
    ownerId: 'usr_101',
    privacyState: 'private',
    agentId: 'usr_101',
    createdAt: '۱۴۰۳/۰۷/۰۲',
  },
  {
    id: 'flw_4',
    title: 'تماس بررسی رضایت مالک دفتر اداری میدان کاج',
    propertyId: 'prop_4',
    propertyTitle: 'موقعیت اداری ۹۰ متر تابلوخور، میدان کاج',
    dueDate: 'دیروز',
    dueTime: '۱۵:۰۰',
    priority: 'medium',
    status: 'overdue',
    type: 'call',
    notes: 'آقای بهرامی گفتند در صورت توافق رهن و اجاره قابل تبدیل است.',
    ownerId: 'usr_102',
    privacyState: 'private',
    agentId: 'usr_102',
    createdAt: '۱۴۰۳/۰۷/۰۱',
  },
];

export const initialMatches: Match[] = [
  {
    id: 'match_1',
    propertyId: 'prop_1',
    property: initialProperties[0],
    clientId: 'cli_1',
    client: initialClients[0],
    matchScore: 96,
    matchedFactors: [
      'بودجه خرید ۲۲.۵ میلیارد در بازه مدنظر مشتری (۲۰ تا ۲۴ م.ت)',
      'محله دقیقاً سعادت‌آباد صراف‌ها',
      'تعداد ۳ خواب و متراژ ۱۴۵ متر',
      'دارای ۲ پارکینگ سندی و آسانسور مورد تقاضا',
    ],
    status: 'new',
    createdAt: '۱۴۰۳/۰۷/۰۴',
  },
  {
    id: 'match_2',
    propertyId: 'prop_2',
    property: initialProperties[1],
    clientId: 'cli_2',
    client: initialClients[1],
    matchScore: 92,
    matchedFactors: [
      'رهن و اجاره در توان پرداختی خانم دکتر معتمدی',
      'متراژ ۱۱۰ متر و ۲ خوابه نوساز',
      'نگهبانی مقیم و محله آرام سعادت‌آباد',
    ],
    status: 'new',
    createdAt: '۱۴۰۳/۰۷/۰۳',
  },
  {
    id: 'match_3',
    propertyId: 'prop_3',
    property: initialProperties[2],
    clientId: 'cli_3',
    client: initialClients[2],
    matchScore: 88,
    matchedFactors: [
      'ویلایی مستقل در نیاوران منطقه ۱',
      'بودجه همخوانی ۸۵ میلیارد تومان',
      'استخر ۴ فصل و متراژ بالای ۴۰۰ متر',
    ],
    status: 'reviewed',
    createdAt: '۱۴۰3/07/02',
  },
];

export const initialOpportunities: Opportunity[] = [
  {
    id: 'opp_1',
    title: 'فروش آپارتمان ۱۴۵ متری به مهندس پارسا',
    clientId: 'cli_1',
    clientName: 'مهندس فرشید پارسا',
    propertyId: 'prop_1',
    propertyTitle: 'آپارتمان ۱۴۵ متری صراف‌ها',
    stage: 'negotiation',
    estimatedValue: 22_500_000_000,
    estimatedCommission: 112_500_000, // 0.5% commission
    probabilityPercent: 75,
    ownerId: 'usr_101',
    privacyState: 'private',
    agentId: 'usr_101',
    notes: 'مشتری ملک را پسندیده؛ سر قیمت متری ۲ میلیون تومان اختلاف دارند که در جلسه نشست حل می‌شود.',
    expectedCloseDate: '۱۴۰۳/۰۷/۱۰',
    createdAt: '۱۴۰۳/۰۷/۰۲',
    updatedAt: '۱۴۰۳/۰۷/۰۴',
  },
  {
    id: 'opp_2',
    title: 'اجاره ۱۱۰ متری فرهنگ به دکتر معتمدی',
    clientId: 'cli_2',
    clientName: 'خانم دکتر معتمدی',
    propertyId: 'prop_2',
    propertyTitle: '۱۱۰ متری بلوار فرهنگ',
    stage: 'contract_pending',
    estimatedValue: 2_400_000_000,
    estimatedCommission: 24_000_000,
    probabilityPercent: 90,
    ownerId: 'usr_101',
    privacyState: 'shared',
    agentId: 'usr_101',
    notes: 'چک‌های اجاره نوشته شده، تاریخ تحویل اول آبان.',
    expectedCloseDate: '۱۴۰۳/۰۷/۰۶',
    createdAt: '۱۴۰۳/۰۷/۰۱',
    updatedAt: '۱۴۰۳/۰۷/۰۴',
  },
  {
    id: 'opp_3',
    title: 'خرید ویلای گل‌سنگ توسط حاج علیرضا اکبری',
    clientId: 'cli_3',
    clientName: 'حاج علیرضا اکبری',
    propertyId: 'prop_3',
    propertyTitle: 'ویلای ۴۵۰ متری نیاوران',
    stage: 'viewing_scheduled',
    estimatedValue: 85_000_000_000,
    estimatedCommission: 425_000_000,
    probabilityPercent: 50,
    ownerId: 'usr_102',
    privacyState: 'private',
    agentId: 'usr_102',
    notes: 'بازدید اول پنج‌شنبه با حضور خانواده انجام خواهد شد.',
    expectedCloseDate: '۱۴۰۳/۰۷/۲۵',
    createdAt: '۱۴۰۳/۰۶/۲۹',
    updatedAt: '۱۴۰۳/۰۷/۰۳',
  },
];

export const initialVisits: Visit[] = [
  {
    id: 'vst_1',
    propertyId: 'prop_1',
    propertyTitle: 'آپارتمان ۱۴۵ متری، صراف‌های جنوبی',
    propertyDistrict: 'سعادت‌آباد',
    clientId: 'cli_1',
    clientName: 'مهندس فرشید پارسا',
    clientPhone: '۰۹۱۲۵۵۵۹۸۷۶',
    scheduledDate: 'امروز',
    scheduledTime: '۱۷:۰۰',
    status: 'scheduled',
    ownerId: 'usr_101',
    privacyState: 'private',
    agentId: 'usr_101',
    createdAt: '۱۴۰۳/۰۷/۰۳',
  },
  {
    id: 'vst_2',
    propertyId: 'prop_3',
    propertyTitle: 'ویلای ۴۵۰ متری نیاوران',
    propertyDistrict: 'نیاوران',
    clientId: 'cli_3',
    clientName: 'حاج علیرضا اکبری',
    clientPhone: '۰۹۱۲۷۷۷۸۸۹۹',
    scheduledDate: 'فردا پنج‌شنبه',
    scheduledTime: '۱۱:۳۰',
    status: 'scheduled',
    ownerId: 'usr_101',
    privacyState: 'private',
    agentId: 'usr_101',
    createdAt: '۱۴۰۳/۰۷/۰۲',
  },
  {
    id: 'vst_3',
    propertyId: 'prop_2',
    propertyTitle: '۱۱۰ متری بلوار فرهنگ',
    propertyDistrict: 'سعادت‌آباد',
    clientId: 'cli_2',
    clientName: 'خانم دکتر معتمدی',
    clientPhone: '۰۹۱۲۶۶۶۳۲۱۰',
    scheduledDate: 'دیروز',
    scheduledTime: '۱۹:۰۰',
    status: 'completed',
    feedback: 'نورگیر و سکوت عالی ارزیابی شد؛ اعلام آمادگی برای تنظیم قرارداد.',
    clientInterestLevel: 'high',
    ownerId: 'usr_102',
    privacyState: 'private',
    agentId: 'usr_102',
    createdAt: '۱۴۰۳/۰۷/۰۱',
  },
];

export const initialNotifications: Notification[] = [
  {
    id: 'notif_1',
    userId: 'usr_101',
    title: 'تطابق جدید هوشمند (۹۶٪)',
    message: 'فایل ۱۴۵ متری صراف‌ها با خریدار فعال مهندس فرشید پارسا تطابق کامل دارد.',
    type: 'match',
    read: false,
    link: '/matches',
    createdAt: '۱۰ دقیقه پیش',
  },
  {
    id: 'notif_2',
    userId: 'usr_101',
    title: 'یادآوری پیگیری معوقه',
    message: 'استعلام سند تک‌برگ ملک نیاوران موعدش گذشته است.',
    type: 'followup',
    read: false,
    link: '/follow-ups',
    createdAt: '۱ ساعت پیش',
  },
  {
    id: 'notif_3',
    userId: 'usr_101',
    title: 'هماهنگی بازدید عصر امروز',
    message: 'ساعت ۱۷:۰۰ بازدید آپارتمان صراف‌ها برای آقای مهندس پارسا ثبت شده است.',
    type: 'visit',
    read: true,
    link: '/visits',
    createdAt: '۳ ساعت پیش',
  },
];
